### ISSUE TITLE
ownCloud Name Normalization issue

### ISSUE THREAD

**Issue by jedunbar** [elie195/duo_provider#11]
Hi, Elie.

I am running ownCloud 10.0 w/ the latest Duo app. Is there a way to enable and enforce ownCloud users to log on with "domain\user" instead of "user"? I currently have Name Normalization turned off for our Duo users because we share a license with our parent company, which forces us to use "domain\user" instead of just "user". ownCloud's logon interface doesn't allow you to specify a domain, so it leaves us dead in the water for using Duo since it requires it.

Thoughts?

**Comment by elie195** [comment]
I'm not sure I fully understand the issue, but have you tried using user@domain instead of domain\user? OwnCloud should let you login with either format from my understanding.

**Comment by elie195** [comment]
Also, are you using the sAMAccountName attribute for authentication or something else? See the LDAP Integration notes in the README for more info.

**Comment by jedunbar** [comment]
Yes, I'm currently using sAMAccountName. I've also tried using userPrincipleName, too, to no avail.

user@domain.com works for authenticating to Active Directory in ownCloud, but once it gets passed to Duo for the second factor, it gets rejected because Duo is explicitly looking for "domain\user" and not "user@domain.com". This wouldn't be a problem if I could use name normalization, but I cannot in our scenario.

**Comment by elie195** [comment]
Got it. I'll be able to look into this further this weekend, since I'd like to try and reproduce a similar environment to yours. 

Assuming there is no solution on the ownCloud or Duo sides, would it help to have an option in the Duo plugin to normalize the usernames to "user" when user@domain or domain\user are passed in? This would only affect the username passed to Duo, ownCloud itself would still see the non-sanitized username.

**Comment by jedunbar** [comment]
Elie,

It would only help if you could do it the other way around. ownCloud takes "user" and passes it to Duo "domain\user".

Is there not a way to force ownCloud to support "domain\user" by itself?

**Comment by elie195** [comment]
After researching it a bit, I don't think ownCloud supports domain\user (netbios name\samaccountname), only user@domain (UPN).

I will work on adding a setting to the Duo plugin which will allow setting a NetBIOS domain name (the domain name before the backslash), then (if enabled), will pass this NetBIOS name + backslash + user to Duo. ETA is about a week.

**Comment by elie195** [comment]
I implemented the feature, but wasn't able to fully test, since my users in Duo aren't in the "domain\user" format. I tested by enabling the feature and configuring the app in Duo with Simple "Username normalization".

Please let me know if the feature doesn't work as expected.

**Comment by jedunbar** [comment]
Elie,

Is there a way to update the Duo app without having to reinstall it? I tried updating it via Marketplace within my ownCloud Settings Panel, but it didn't actually update the Duo app. It said it updated to the latest version, but still shows in Apps as the previous version. Thoughts?

**Comment by elie195** [comment]
Interesting, I didn't run into this behavior in my environment. The Marketplace is something fairly new, so I'll need to do some testing in my environment in order to reproduce before I can try to fix it. I'll try to at least have it reproduced by the end of this week.

**Comment by jedunbar** [comment]
Do you know what the current method for updating apps is? Do I need to reinstall the app from scratch?

**Comment by elie195** [comment]
You should be able to just extract the contents of the zip file to the app's installation directory (apps/duo in your ownCloud install dir) and overwrite the existing files. The config settings of the app shouldn't be affected, since they are outside of the app's install dir.

After you have overwritten the directory with the new version, ownCloud should prompt you to "upgrade" your installation either via the web UI, or via the "occ upgrade" CLI command. 

I would take a VM snapshot before trying this just in case (if possible)

**Comment by elie195** [comment]
I have attempted to reproduce this with a fresh install of the latest production version available on owncloud.org (10.0.2), but was not able to. I was able to go from 2.1.0 (installed from marketplace.owncloud.org ZIP file) to 2.2.0 completely through the Marketplace GUI. The app then showed as 2.2.0 in "Apps", and had the new advanced option (in the "Additional" section, click "Show advanced").

If you have tried this already, just to confirm, what Duo (this app) version are you coming from/what is it showing?
